---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "C:/Users/joaoc/OneDrive - A2itwb Tecnologia S.A/02. NAPymiko/inputfiles/inventory/hosts.yaml"
        group_file: "C:/Users/joaoc/OneDrive - A2itwb Tecnologia S.A/02. NAPymiko/inputfiles/inventory/groups.yaml"
        defaults_file: "C:/Users/joaoc/OneDrive - A2itwb Tecnologia S.A/02. NAPymiko/inputfiles/inventory/defaults.yaml"
runner:
    plugin: threaded
    options:
        num_workers: 40
user_defined:
    NAPymiko_data:
        device_configuration:
            group: Device
            label: Configuration
            status: enabled
            commands:
                alcatel_aos:
                    - show configuration snapshot
                cisco_ios:
                    - show running-config
                cisco_nxos:
                    - show running-config
                extreme:
                    - show config
                extreme_exos:
                    - show config
        device_information:
            group: Device
            label: Information
            status: enabled
            commands:
                cisco_ios:
                    - show version
                cisco_nxos:
                    - show version
                extreme:
                    - show system
                    - show time
                    - show system hardware
                extreme_exos:
                    - show system
        device_file_system:
            group: Device
            label: Directory
            status: disabled
            commands:
                cisco_ios:
                    - dir
                    - show file system
                cisco_nxos:
                    - dir
                    - show file system
        device_management:
            group: Device
            label: Management
            status: enabled
            commands:
                extreme:
                    - show ssh
                    - show telnet
                    - show webview
                extreme_exos:
                    - show management
        device_license:
            group: Device
            label: Status
            status: disabled
            commands:
                cisco_ios:
                    - show license status
        device_power_information:
            group: Device
            label: Power Information
            status: enabled
            commands:
                extreme:
                    - show system
                extreme_exos:
                    - show power detail
        interface_statistics:
            group: Interface
            label: Statistics
            status: disabled
            commands:
                cisco_ios:
                    - show interfaces counters
        interface_information:
            group: Interface
            label: Information
            status: enabled
            commands:
                cisco_ios:
                    - show interfaces
                extreme_exos:
                    - show ports information detail
        interface_status:
            group: Interface
            label: Status
            status: enabled
            commands:
                extreme:
                    - show port status
                extreme_exos:
                    - show ports no-refresh
        transceiver_information:
            group: Interface
            label: Transceiver Information
            status: enabled
            commands:
                extreme:
                    - show port transceiver basic-only
                extreme_exos:
                    - show ports transceiver information detail
        snmp_access:
            group: Monitoring
            label: SNMP Access
            status: enabled
            commands:
                extreme_exos:
                    - show snmpv3 access
        snmp_community:
            group: Monitoring
            label: SNMP Community
            status: enabled
            commands:
                extreme_exos:
                    - show snmpv3 community
        snmp_filter_profile:
            group: Monitoring
            label: SNMP Filter Profile
            status: enabled
            commands:
                extreme_exos:
                    - show snmpv3 fiter-profile
        snmp_filter:
            group: Monitoring
            label: SNMP Filter
            status: enabled
            commands:
                extreme_exos: 
                    - show snmpv3 fiter
        snmp_group:
            group: Monitoring
            label: SNMP Group
            status: enabled
            commands:
                extreme_exos: 
                    - show snmpv3 group
        snmp_traps:
            group: Monitoring
            label: SNMP Traps
            status: enabled
            commands:
                extreme_exos: 
                    - show snmpv3 traps
        snmp_server:
            group: Monitoring
            label: SNMP Server
            status: enabled
            commands:
                extreme_exos: 
                    - show snmpv3 target-addr
        snmp_target_parameters:
            group: Monitoring
            label: SNMP Target Parameters
            status: enabled
            commands:
                extreme_exos:
                    - show snmpv3 target-params
        snmp_user:
            group: Monitoring
            label: SNMP User
            status: enabled
            commands:
                extreme_exos: 
                    - show snmpv3 user
        cdp_neighbors:
            group: Discovery Protocols
            label: CDP Neighbors
            status: enabled
            commands:
                cisco_ios: 
                    - show cdp neighbors detail
                cisco_nxos: 
                    - show cdp neighbors detail
                cisco_wlc: 
                    - show cdp neighbors detail
                extreme: 
                    - show neighbors
                extreme_exos: 
                    - show cdp neighbor detail
        lldp_neighbors:
            group: Discovery Protocols
            label: LLDP Neighbors
            status: enabled
            commands:
                alcatel_aos: 
                    - show lldp remote-system
                cisco_ios: 
                    - show lldp neighbors detail
                cisco_nxos: 
                    - show lldp neighbors detail
                extreme: 
                    - show lldp port remote-info
                extreme_exos:
                    - show lldp neighbor detailed
        cdp_configuration:
            group: Discovery Protocols
            label: CDP Configuration
            status: enabled
            commands:
                extreme: 
                    - show ciscodp
                extreme_exos:
                    - show cdp
        # cdp_diagram:
        #     group: Network Diagram
        #     label: CDP Neighbors Diagram
        #     status: enabled
        #     commands:
        #         cisco_ios:
        #             - show cdp neighbors detail
        #         cisco_nxos:
        #             - show cdp neighbors detail
        #         cisco_wlc:
        #             - show cdp neighbors detail
        #         extreme:
        #             - show neighbors
        #         extreme_exos:
        #             - show cdp neighbor detail
        # lldp_diagram:
        #     group: Network Diagram
        #     label: LLDP Neighbors Diagram
        #     status: enabled
        #     commands:
        #         alcatel_aos:
        #             - show lldp remote-system
        #         cisco_ios:
        #             - show lldp neighbors detail
        #         cisco_nxos:
        #             - show lldp neighbors detail
        #         extreme:
        #             - show lldp port remote-info
        #         extreme_exos:
        #             - show lldp neighbor detailed
        local_users:
            group: Others
            label: Local Users
            status: enabled
            commands:
                extreme:
                    - show system login
                extreme_exos:
                    - show accounts
        mac_address_table:
            group: Others
            label: MAC Address Table
            status: disabled
            commands:
                cisco_ios:
                    - show mac address-table
        vlan_ports:
            group: Interface
            label: VLAN Ports
            status: disabled
            commands:
                extreme:
                    - show vlan portinfo
                extreme_exos:
                    - show ports vid port-number